on: push
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.13 release
      uses: AbsaOSS/golang-pipeline/go1.13/release@master
      env:
        PROJECT_PATH: "./cmd/manager"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: linux
        GOARCH: amd64
#        UPLOAD_URL: https://uploads.github.com/repos/kuritka/git-actions/releases/
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

