on: push
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.13 release
      uses: kuritka/golang-pipeline/go1.13/release@master
      env:
        PROJECT_PATH: "./cmd/manager"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: linux
        GOARCH: amd64
#        UPLOAD_URL: https://uploads.github.com/repos/kuritka/git-actions/releases/
#      with:
#        upload_url: ${{ https://api.github.com/repos/kuritka/git-actions/releases/1/assets }}
#        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#        asset_path: ./my-artifact.zip
#        asset_name: my-artifact.zip
#        asset_content_type: application/zip


