#on: release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


#on: release
name: build on release
jobs:
  build:
    name: Go RELEASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go1.13 release linux
        uses: shoukoo/golang-pipeline/go1.13/release@master
#       if: github.event.action == 'published'
        env:
          PROJECT_PATH: "./cmd/manager"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: linux
          GOARCH: amd64
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          upload_url: ${{ github.event.release.release.upload_url }}



