on:
  release:
    types: [published]

name: build on release
jobs:
  build:
    name: Go RELEASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go1.14 release linux
        uses: shoukoo/golang-pipeline/go1.14/release@master
        env:
          #when path different than root
          PROJECT_PATH: "./cmd/manager"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: linux
          GOARCH: amd64
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}




